#!/bin/sh
set -e

version=KERNELVER-chrultrabook-stoney
image_path=/boot/vmlinuz-$version

rm -f /lib/modules/$version/.fresh-install

if [ "$1" != upgrade ] && command -v linux-update-symlinks >/dev/null; then
    linux-update-symlinks remove $version $image_path
fi

if [ -d /etc/kernel/postrm.d ]; then
    # We cannot trigger ourselves as at the end of this we will no longer
    # exist and can no longer respond to the trigger.  The trigger would
    # then become lost.  Therefore we clear any pending trigger and apply
    # postrm directly.
    if [ -f /usr/lib/linux/triggers/$version ]; then
	echo "$0 ... removing pending trigger"
	rm -f /usr/lib/linux/triggers/$version
    fi
    DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
	      --arg=$image_path /etc/kernel/postrm.d
fi

if [ "$1" = purge ]; then
    for extra_file in modules.dep modules.isapnpmap modules.pcimap \
                      modules.usbmap modules.parportmap \
                      modules.generic_string modules.ieee1394map \
                      modules.ieee1394map modules.pnpbiosmap \
                      modules.alias modules.ccwmap modules.inputmap \
                      modules.symbols modules.ofmap \
                      modules.seriomap modules.\*.bin \
		      modules.softdep modules.devname; do
	eval rm -f /lib/modules/$version/$extra_file
    done
    rmdir /lib/modules/$version || true
fi

### MODULES
if [ "$1" != remove ]; then
    exit 0
fi

depmod -a -F /boot/System.map-$version $version 2>/dev/null || true
#
# We should be rebuilding the initramfs here on removal to pare down the
# initramfs if it contains any of the objects we just removed.  But people
# commonly remove kernels in order to free space in /boot, and rebuilding the
# initramfs now risks ENOSPC when we are trying to make space.  The files we
# leave lying about could be confusing, but we trade that against safety on
# removal.
#
#if [ -d /etc/kernel/postinst.d ]; then
#    # We want to behave as if linux-image (without us) was installed, therefore
#    # we do not want the postinst support to know we are being removed, claim
#    # this is an installation event.
#    cat - >/usr/lib/linux/triggers/$version <<EOF
#DEB_MAINT_PARAMS="configure" run-parts --report --exit-on-error --arg=$version \
#	--arg="$image_path" /etc/kernel/postinst.d
#EOF
#    dpkg-trigger --no-await linux-update-$version
#fi
###

exit 0
